pluginGroup=com.ericfortis.tailwindeye
pluginName=Tailwind Eye
pluginRepositoryUrl=https://github.com/ericfortis/tailwind-eye
pluginVersion=0.0.2
pluginSinceBuild=261
platformVersion=2026.1
platformPlugins=
platformBundledPlugins=com.intellij.react,intellij.json,com.intellij.css
platformBundledModules=
gradleVersion=9.6.1
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
